name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different
      - feature/*  # Optional: Deploy on feature branches as well

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Build production
        run: npm run build --configuration=production --base-href=/ng-news-app/

      - name: Deploy to gh pages
        run: npx ng deploy --base-href=/ng-news-app/
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
